version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thredded_dev
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  web:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_DATABASE: thredded_dev
      DB_USERNAME: root
      DB_PASSWORD: root
      SECRET_KEY_BASE: 3f7e385989131af052c120a6c037d6f4b3caa459a9b0159fd1f212afdf361e4a2c99e4f0159fa24ba92c6aa189002fd5aa479b3e4a8a0093f4fd4d8f2b5cd3c0
    ports:
      - 8080:3000
