development:
  adapter: postgresql
  host: localhost
  database: thredded_demo_dev
  username: postgres
  password:
  encoding: utf8

production:
  url: <%= ENV['DATABASE_URL'].to_json %>
  encoding: utf8
