development:
  adapter: mysql2
  host: db
  database: thredded_dev
  username: root
  password: root
  encoding: utf8

production:
  adapter: mysql2
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_DATABASE"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  encoding: utf8
